// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Note struct {
	ID           int32     `json:"id"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	IsFavorite   bool      `json:"isFavorite"`
	CreatedBy    int32     `json:"createdBy"`
	IDCategory   int32     `json:"idCategory"`
	CreatedAt    string    `json:"createdAt"`
	UpdatedAt    string    `json:"updatedAt"`
	User         *User     `json:"user"`
	Category     *Category `json:"category"`
	ReminderTime *string   `json:"reminderTime,omitempty"`
}

type Query struct {
}

type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
